### ISSUE TITLE
Performans Optimizasyonu 1

### ISSUE THREAD

**Issue by umutphp** [enescelep/AsalSayiKontrol#2]
https://github.com/enescelep/AsalSayiKontrol/blob/803bb44f78e59935e91e0e403228fbe762388278/asalmi.py#L13

Burada range üst sınırını sayının yarısı yaparsan, döngüdeki gereksiz işlemlerden kurtulmuş olursun. Sebebi ise bir sayının yarısından büyük bir çarpanı olamamasıdır.

**Comment by enescelep** [comment]
Düzelttim.
