### ISSUE TITLE
Performans Optimizasyonu 2

### ISSUE THREAD

**Issue by umutphp** [enescelep/AsalSayiKontrol#3]
https://github.com/enescelep/AsalSayiKontrol/blob/803bb44f78e59935e91e0e403228fbe762388278/asalmi.py#L16

**if carpanSayisi >** 2 kontrolünü for döngüsü içinde yaparsan, çarpansayısı 3 ten büyük olan durumlarda boşuna döngüye devam etmemiş olursun.

**Comment by enescelep** [comment]
Düzelttim.
